title: Pigeon Town
description: >-
  A photoblog about pigeons, around the city and elsewhere.
baseurl: "/pigeon_town"
url: "https://blackavar2121.github.io"

# Flickr
flickr_username: blackavar21

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Permalink style â€” clean URLs
permalink: /:year/:month/:day/:title/

# Exclude dev files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
